version: "3.9"

services:
  java-app:
    container_name: java-app
    hostname: java-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAVA_VERSION=${JAVA_VERSION:-17}
    image: java-app:${JAVA_VERSION}
    environment:
      - HOSTNAME=java-app
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "User-Agent: Docker", "http://localhost:8085/actuator/health"] # Verifica que el proceso Java est√© corriendo
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    user: root
