server:
  port: 8082

spring:
  application:
    name: dispatch-consumer
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:root@localhost:27017}
      database: bank
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

kafka:
  topic: bank.card.replacements.v1
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
  group-id: dispatch.consumer.v1

