version: "3.9"


services:
  dispatch-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    image: verdugox/dispatch-consumer:latest
    container_name: dispatch-consumer
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      REDIS_HOST: redis
      # Agregamos autenticaci√≥n porque tu Mongo tiene root/root
      MONGODB_URI: mongodb://root:root@mongodb:27018/bank_db?authSource=admin
    ports: [ "8082:8082" ]
    networks:
      - bank-network


networks:
  bank-network:
    external: true
    name: bank-network # Asegura que busque exactamente este nombre
