
volumes:
  app-logs-shared:
    external: true
  cw-config:
    external: true

networks:
  bank-network:
    external: true

services:
  consumer-app:
    container_name: consumer-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAVA_VERSION=${JAVA_VERSION:-17}
    image: java-app:${JAVA_VERSION}
    ports:
      - "${APP_PORT:-8082}:8082"  # <-- Puerto configurable: HOST:CONTAINER
    volumes:
      - app-logs-shared:/app/logs:rw # <-- ¡MONTAMOS LA CARPETA DE LOGS EN EL VOLUMEN COMPARTIDO
      # Si tu app escribe logs en /app/logs dentro del contenedor, aparecerán en ./logs del host.
    environment:
       # --- CAMBIO CRÍTICO: USAR NOMBRES DE CONTENEDORES ---

       # Redis: Usamos 'redis-bank' (el container_name del otro archivo)
       - REDIS_HOST=redis-bank
       - REDIS_PORT=6379

       # Kafka: Usamos 'kafka' y el puerto INTERNO (9092)
       - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
       - SCHEMA_REGISTRY_URL=http://schema-registry:8081

       # Mongo: Usamos 'mongo-bank' y el puerto INTERNO (27017)
       - MONGODB_URI=mongodb://root:root@mongo-bank:27017/bank?authSource=admin
    networks:
      - bank-network
    # Healthcheck simple para apps que no son web (como nuestro ejemplo)
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "User-Agent: Docker", "http://localhost:8085/actuator/health"] # Verifica que el proceso Java esté corriendo
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    user: root