server:
  port: 8085

spring:
  application:
    name: card-ops-producer
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topic: bank.card.replacements.v1
  schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

resilience4j:
  circuitbreaker:
    instances:
      kafkaPublisher:
        failureRateThreshold: 50
        waitDurationInOpenState: 5000ms
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      kafkaPublisher:
        maxAttempts: 3
        waitDuration: 100ms