version: "3.9"


# Definimos una red para que todos se vean entre sí por nombre
networks:
  bank-network:
    external: true

services:
  # --- INFRAESTRUCTURA KAFKA ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: [ "2181:2181" ]
    networks:
      - bank-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka
    container_name: kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Configuración robusta para acceso interno (contenedores) y externo (tu PC)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bank-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on: [ kafka ]
    ports: [ "8081:8081" ]
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    networks:
      - bank-network

  # --- CACHÉ Y BASE DE DATOS ---
  redis:
    image: redis/redis-stack-server:7.2.0-v14
    container_name: redis-bank
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bank-network
    command: >
      redis-server
      --bind 0.0.0.0
      --port 6379
      --maxmemory 8gb
      --protected-mode no
      --maxmemory-policy allkeys-lfu
      --dir /data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Redis-produccion", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb:
    image: mongo:6
    container_name: mongo-bank
    ports: [ "27018:27017" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
    networks:
      - bank-network

  # --- CALIDAD (SonarQube) ---
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - bank-network




# Definimos volúmenes para no perder datos al reiniciar
volumes:
  mongo_data:
  redis_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: